export enum CountryEnum {
  Bahrain = "Bahrain",
  Cyprus = "Cyprus",
  Egypt = "Egypt",
  Iran = "Iran",
  Iraq = "Iraq",
  Israel = "Israel",
  Jordan = "Jordan",
  Kuwait = "Kuwait",
  Lebanon = "Lebanon",
  Oman = "Oman",
  Qatar = "Qatar",
  Saudi_Arabia = "Saudi Arabia",
  Syria = "Syria",
  Turkey = "Turkey",
  United_Arab_Emirates = "United Arab Emirates",
  Yemen = "Yemen",
}
